# Generated by Django 3.2.13 on 2022-10-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_song_date_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.lyrics'),
            preserve_default=False,
        ),
    ]
