# Generated by Django 3.2.13 on 2022-11-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_song_lyrics_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics_id',
        ),
    ]
